[package]
name = "cli-interface"
version.workspace = true
edition.workspace = true
authors.workspace = true


[dependencies]
clap.workspace = true
colored.workspace = true
engine.workspace = true
anyhow.workspace = true
indicatif.workspace = true
log.workspace = true